name: Build and Test Prometheus Exporter

on: [push, pull_request]

jobs:
  Get-CI-Image-Tag:
    uses: opensearch-project/opensearch-build/.github/workflows/get-ci-image-tag.yml@main
    with:
      product: opensearch

  linux-build:
    needs: Get-CI-Image-Tag
    strategy:
      matrix:
        java: [21]
    runs-on: ubuntu-latest
    container:
      image: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-version-linux }}
      options: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-start-options }}
    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      JAVA_TOOL_OPTIONS: -Dfile.encoding=UTF-8
    steps:
      - name: Run start commands
        run: ${{ needs.Get-CI-Image-Tag.outputs.ci-image-start-command }}
      - uses: actions/checkout@v5
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: ${{ matrix.java }}
      - name: Build with Gradle
        run: |
          chown -R 1000:1000 `pwd`
          su `id -un 1000` -c "./gradlew --info build"
      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
      - name: Create Artifact Path
        run: |
          mkdir -p prometheus-exporter-builds
          cp -r ./build/distributions/*.zip prometheus-exporter-builds/
          chown -R 1000:1000 `pwd`
      - name: Upload Artifacts
        uses: actions/upload-artifact@v5
        with:
          name: prometheus-exporter-linux-${{ matrix.java }}
          path: prometheus-exporter-builds